services:
  master-bot:
    build: .
    depends_on: 
      - mongo
    links:
      - mongo
    restart: always
  mongo:
    image: mongo:4-focal
    volumes:
      - ./db/mongo:/data/db
    restart: always
